import LandingLayout from "@/components/layouts/landing";
import { DialogProvider } from "@/contexts/dialog.context";
import { LoadingProvider } from "@/contexts/loading.context";
import { ReactQueryProviders } from "@/providers/react-query-provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Café Street",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ReactQueryProviders>
          <LandingLayout>{children}</LandingLayout>
          <DialogProvider />
          <LoadingProvider />
          <ToastContainer />
        </ReactQueryProviders>
      </body>
    </html>
  );
}
